name: Update this repo's README with RSS feeds

on:
  push:
    branches: [ master ]
  schedule:
    # each 6h
    - cron: 0 */6 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/JasonEtco/rss-to-readme
      - uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://blog.kartones.net/syndication.rss
          readme-section: feed
          max: 5
